version: 2
updates:
  # Maintain dependencies for Maven in the v2.x branch
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: v2.x
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

  # Maintain dependencies for Maven in the v2.2.x branch
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: v2.2.x
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

  # Maintain dependencies for Maven in the v2.1.x branch
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: v2.1.x
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

  # Maintain dependencies for Maven in the v2.0.x branch
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: v2.0.x
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "org.jooq:jooq"
        versions: ["[3.17,)"]
      - dependency-name: "org.liquibase:liquibase-core"
        versions: ["[4.12,)"]
      - dependency-name: "org.openjfx"
        versions: ["[19.0,)"]

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: v2.x
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

